### ISSUE TITLE
The people want a cowsay integration!

### ISSUE THREAD

**Issue by TomGranot** [wohb/okify#7]
@noisleahcim  A sentence I never thought I'd say: happy running into you on Linkedin

https://www.linkedin.com/feed/update/urn:li:activity:6729788954465329152?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A6729788954465329152%2C6730039798813224960%29&replyUrn=urn%3Ali%3Acomment%3A%28activity%3A6729788954465329152%2C6730040918524600320%29

**Comment by noisleahcim** [comment]
Amazing suggestion.
Important to note that there is no issue at all and everything is already perfect.

**Comment by TomGranot** [comment]
Incorrect - you can never have enough cows @noisleahcim
